name: "jec-trial"
network_config: networks/pfn_regressor.py
data_config: data/jec_pfn.yaml
model_prefix: outputs/{auto}/net
log: logs/{auto}.log
parameters:
  - name: --start-lr
    parameterType: double
    feasibleSpace:
      min: "1.0e-5"
      max: "1.0e-4"
  - name: --optimizer
    parameterType: categorical
    feasibleSpace:
      list:
        - "adam"
        - "adamW"
        - "ranger"
  - name: --num-epochs
    parameterType: discrete
    feasibleSpace:
      list:
        - "2"
  - name: --batch-size
    parameterType: discrete
    feasibleSpace:
      list:
        - "100"
  - name: --data-fraction
    parameterType: categorical
    feasibleSpace:
      list:
        - "0.001"
data:
  train:
    - /eos/cms/store/group/phys_jetmet/dholmber/jec-data/001.root
    - /eos/cms/store/group/phys_jetmet/dholmber/jec-data/002.root
  val:
    - /eos/cms/store/group/phys_jetmet/dholmber/jec-data/003.root
  test:
    - /eos/cms/store/group/phys_jetmet/dholmber/jec-data/004.root