apiVersion: v1
kind: Secret
metadata:
  name: s3-secret
  annotations:
     serving.kubeflow.org/s3-endpoint: s3.cern.ch
type: Opaque
stringData:
  awsAccessKeyID: ""
  awsSecretAccessKey: ""
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: sa
secrets:
- name: s3-secret