apiVersion: kubeflow.org/v1alpha3
kind: Experiment
metadata:
  name:
  namespace:
spec:
  parallelTrialCount: 1
  maxTrialCount: 2
  maxFailedTrialCount: 1
  objective:
    type: minimize
    objectiveMetricName: Loss
    additionalMetricNames:
        - AvgLoss
        - MSE
        - AvgMSE
        - MAE
        - AvgMAE
  algorithm:
    algorithmName: random
  metricsCollectorSpec:
    collector:
      kind: StdOut
  parameters:
  trialTemplate:
    goTemplate:
      rawTemplate: |-
        apiVersion: kubeflow.org/v1
        kind: PyTorchJob
        metadata:
          name: {{.Trial}}
          namespace: {{.NameSpace}}
        spec:
         pytorchReplicaSpecs:
          Master:
            replicas: 1
            restartPolicy: OnFailure
            template:
              spec:
                volumes:
                  - name: eos
                    hostPath:
                      path: /var/eos
                  - name: krb-secret-vol
                    secret:
                      secretName: krb-secret
                  - name: nvidia-driver
                    hostPath:
                      path: /opt/nvidia-driver
                      type: ""
                containers:
                  - name: pytorch
                    resources: 
                      limits:
                        cpu: 1
                    volumeMounts:
                      - name: eos
                        mountPath: /eos
                      - name: krb-secret-vol
                        mountPath: /secret/krb-secret-vol
                      - name: nvidia-driver
                        mountPath: /opt/nvidia-driver
                    image: gitlab-registry.cern.ch/dholmber/jec-pipeline/weaver:training_c9d3590d
                    command: [sh, -c]
                    args:
                      - whoami;
                        cp /secret/krb-secret-vol/krb5cc_1000 /tmp/krb5cc_1000;
                        chmod 600 /tmp/krb5cc_1000;
                        python train.py
                        --regression-mode
                        --num-workers "1"
                        --gpus ""
                        --data-train
                        --data-val
                        --data-test
                        --network-config
                        --data-config
                        --model-prefix
                        --log
                        {{- with .HyperParameters}}
                        {{- range .}}
                        {{.Name}} {{.Value}}
                        {{- end}}
                        {{- end}}

