apiVersion: kubeflow.org/v1
kind: PyTorchJob
metadata:
  name: JOB_NAME
  namespace: NAMESPACE
spec:
  pytorchReplicaSpecs:
    Master:
      replicas: 1
      restartPolicy: Never
      template:
        metadata:
          annotations:
            sidecar.istio.io/inject: "false"
        spec:
          volumes:
            - name: eos
              hostPath:
                path: /var/eos
            - name: krb-secret-vol
              secret:
                secretName: krb-secret
            - name: nvidia-driver
              hostPath:
                path: /opt/nvidia-driver
                type: ""
          containers:
            - name: pytorch
              resources: 
                limits:
                  cpu: 2
                  memory: 12Gi
                requests:
                  cpu: 1
                  memory: 8Gi
              volumeMounts:
                - name: eos
                  mountPath: /eos
                - name: krb-secret-vol
                  mountPath: /secret/krb-secret-vol
                - name: nvidia-driver
                  mountPath: /opt/nvidia-driver
              env:
                - name: AWS_ACCESS_KEY_ID
                  valueFrom:
                    secretKeyRef:
                      key: AWS_ACCESS_KEY_ID
                      name: s3-secret
                - name: AWS_SECRET_ACCESS_KEY
                  valueFrom:
                    secretKeyRef:
                      key: AWS_SECRET_ACCESS_KEY
                      name: s3-secret
              image: registry.cern.ch/ml/weaver:latest
              command:
                - python
                - train.py
              args:
                - --data-config=DATA_CONFIG
                - --network-config=NETWORK_CONFIG
                - --network-option=NETWORK_OPTION
                - --model-prefix=PT_PATH
                - --export-onnx=ONNX_PATH
                - --triton-config=TRITON_CONFIG