apiVersion: kubeflow.org/v1beta1
kind: Experiment
metadata:
  name: EXPERIMENT_NAME
  namespace: NAMESPACE
spec:
  parallelTrialCount: 2
  maxTrialCount: 2
  maxFailedTrialCount: 1
  objective:
    type: minimize
    objectiveMetricName: Loss
    additionalMetricNames:
      - AvgLoss
      - MSE
      - AvgMSE
      - MAE
      - AvgMAE
  algorithm:
    algorithmName: random
  metricsCollectorSpec:
    collector:
      kind: StdOut
  parameters:
    - name: start-lr
      parameterType: double
      feasibleSpace:
        min: "1.0e-5"
        max: "1.0e-4"
    - name: optimizer
      parameterType: categorical
      feasibleSpace:
        list:
          - "adam"
          - "adamW"
          - "ranger"
    - name: num-epochs
      parameterType: discrete
      feasibleSpace:
        list:
          - "5"
    - name: batch-size
      parameterType: discrete
      feasibleSpace:
        list:
          - "100"
    - name: data-fraction
      parameterType: categorical
      feasibleSpace:
        list:
          - "0.001"
  trialTemplate:
    primaryContainerName: pytorch
    trialParameters:
      - name: startLr
        reference: start-lr
        description: ""
      - name: optimizer
        reference: optimizer
        description: ""
      - name: numEpochs
        reference: num-epochs
        description: ""
      - name: batchSize
        reference: batch-size
        description: ""
      - name: dataFraction
        reference: data-fraction
        description: ""
    trialSpec:
      apiVersion: kubeflow.org/v1
      kind: PyTorchJob
      spec:
        pytorchReplicaSpecs:
          Master:
            replicas: 1
            restartPolicy: OnFailure
            template:
              metadata:
                annotations:
                  sidecar.istio.io/inject: "false"
              spec:
                volumes:
                  - name: eos
                    hostPath:
                      path: /var/eos
                  - name: krb-secret-vol
                    secret:
                      secretName: krb-secret
                  - name: nvidia-driver
                    hostPath:
                      path: /opt/nvidia-driver
                      type: ""
                containers:
                  - name: pytorch
                    resources: 
                      limits:
                        cpu:     2
                        memory:  12Gi
                      requests:
                        cpu:      1
                        memory:   8Gi
                    volumeMounts:
                      - name: eos
                        mountPath: /eos
                      - name: krb-secret-vol
                        mountPath: /secret/krb-secret-vol
                      - name: nvidia-driver
                        mountPath: /opt/nvidia-driver
                    env:
                      - name: S3_ENDPOINT
                        value: https://s3.cern.ch
                      - name: AWS_ACCESS_KEY_ID
                        valueFrom:
                          secretKeyRef:
                            key: AWS_ACCESS_KEY_ID
                            name: s3-secret
                      - name: AWS_SECRET_ACCESS_KEY
                        valueFrom:
                          secretKeyRef:
                            key: AWS_SECRET_ACCESS_KEY
                            name: s3-secret
                    image: registry.cern.ch/ml/weaver:latest
                    command:
                      - python
                      - train.py
                    args:
                      - --gpus=
                      - --num-workers=1
                      - --regression-mode
                      - --data-train=DATA_TRAIN
                      - --data-val=DATA_VAL
                      - --data-test=DATA_TEST
                      - --data-config=DATA_CONFIG
                      - --network-config=NETWORK_CONFIG
                      - --start-lr=${trialParameters.startLr}
                      - --optimizer=${trialParameters.optimizer}
                      - --num-epochs=${trialParameters.numEpochs}
                      - --batch-size=${trialParameters.batchSize}
                      - --data-fraction=${trialParameters.dataFraction}
                      - --tensorboard-log-dir=S3_BUCKET/tensorboard/RUN_ID/${trialParameters.startLr}_${trialParameters.optimizer}_${trialParameters.numEpochs}_${trialParameters.batchSize}_${trialParameters.dataFraction}
                      - --s3-model=S3_BUCKET/RUN_ID/${trialParameters.startLr}_${trialParameters.optimizer}_${trialParameters.numEpochs}_${trialParameters.batchSize}_${trialParameters.dataFraction}.pt
