apiVersion: kubeflow.org/v1beta1
kind: Experiment
metadata:
  name: EXPERIMENT_NAME
  namespace: NAMESPACE
spec:
  parallelTrialCount: 2
  maxTrialCount: 30
  maxFailedTrialCount: 1
  objective:
    type: minimize
    objectiveMetricName: Loss
    additionalMetricNames:
      - AvgLoss
      - MSE
      - AvgMSE
      - MAE
      - AvgMAE
  algorithm:
    algorithmName: random
  metricsCollectorSpec:
    collector:
      kind: StdOut
  parameters:
    - name: num-edge-conv-blocks
      parameterType: discrete
      feasibleSpace:
        list:
          - "1"
    - name: k
      parameterType: discrete
      feasibleSpace:
        list:
          - "1"
    - name: num-conv-layers
      parameterType: discrete
      feasibleSpace:
        list:
          - "1"
          - "2"
          - "3"
          - "4"
          - "5"
    - name: conv-dim
      parameterType: discrete
      feasibleSpace:
        list:
          - "50"
          - "100"
          - "200"
          - "400"
    - name: num-fc-layers
      parameterType: discrete
      feasibleSpace:
        list:
          - "1"
          - "2"
          - "3"
          - "4"
          - "5"
    - name: fc-dim
      parameterType: discrete
      feasibleSpace:
        list:
          - "50"
          - "100"
          - "200"
          - "400"
    - name: dropout
      parameterType: double
      feasibleSpace:
        min: "0.0"
        max: "0.5"
    - name: start-lr
      parameterType: double
      feasibleSpace:
        min: "1.0e-5"
        max: "1.0e-2"
    - name: optimizer
      parameterType: categorical
      feasibleSpace:
        list:
          - "adam"
          - "adamW"
          - "ranger"
          - "rmsprop"
          - "adagrad"
    - name: num-epochs
      parameterType: discrete
      feasibleSpace:
        list:
          - "30"
    - name: batch-size
      parameterType: discrete
      feasibleSpace:
        list:
          - "500"
    - name: data-fraction
      parameterType: categorical
      feasibleSpace:
        list:
          - "1"
  trialTemplate:
    primaryContainerName: pytorch
    trialParameters:
      - name: numEdgeConvBlocks
        reference: num-edge-conv-blocks
        description: ""
      - name: k
        reference: k
        description: ""
      - name: numConvLayers
        reference: num-conv-layers
        description: ""
      - name: convDim
        reference: conv-dim
        description: ""
      - name: numFcLayers
        reference: num-fc-layers
        description: ""
      - name: fcDim
        reference: fc-dim
        description: ""
      - name: dropout
        reference: dropout
        description: ""
      - name: startLr
        reference: start-lr
        description: ""
      - name: optimizer
        reference: optimizer
        description: ""
      - name: numEpochs
        reference: num-epochs
        description: ""
      - name: batchSize
        reference: batch-size
        description: ""
      - name: dataFraction
        reference: data-fraction
        description: ""
    trialSpec:
      apiVersion: kubeflow.org/v1
      kind: PyTorchJob
      spec:
        pytorchReplicaSpecs:
          Master:
            replicas: 1
            restartPolicy: OnFailure
            template:
              metadata:
                annotations:
                  sidecar.istio.io/inject: "false"
              spec:
                volumes:
                  - name: eos
                    hostPath:
                      path: /var/eos
                  - name: krb-secret-vol
                    secret:
                      secretName: krb-secret
                  - name: nvidia-driver
                    hostPath:
                      path: /opt/nvidia-driver
                      type: ""
                containers:
                  - name: pytorch
                    resources: 
                      limits:
                        nvidia.com/gpu: NUM_GPUS
                        cpu: 4
                        memory: 12Gi
                      requests:
                        nvidia.com/gpu: NUM_GPUS
                        cpu: NUM_CPUS
                        memory: 8Gi
                    volumeMounts:
                      - name: eos
                        mountPath: /eos
                      - name: krb-secret-vol
                        mountPath: /secret/krb-secret-vol
                      - name: nvidia-driver
                        mountPath: /opt/nvidia-driver
                    env:
                      - name: S3_ENDPOINT
                        value: https://s3.cern.ch
                      - name: AWS_ACCESS_KEY_ID
                        valueFrom:
                          secretKeyRef:
                            key: AWS_ACCESS_KEY_ID
                            name: s3-secret
                      - name: AWS_SECRET_ACCESS_KEY
                        valueFrom:
                          secretKeyRef:
                            key: AWS_SECRET_ACCESS_KEY
                            name: s3-secret
                    image: registry.cern.ch/ml/weaver:latest
                    command:
                      - python
                      - train.py
                    args:
                      - --gpus=GPU_IDS
                      - --num-workers=NUM_CPUS
                      - --backend=BACKEND
                      - --regression-mode
                      - --copy-inputs
                      - --data-train=DATA_TRAIN
                      - --data-val=DATA_VAL
                      - --data-test=DATA_TEST
                      - --data-config=DATA_CONFIG
                      - --network-config=NETWORK_CONFIG
                      - --start-lr=${trialParameters.startLr}
                      - --optimizer=${trialParameters.optimizer}
                      - --num-epochs=${trialParameters.numEpochs}
                      - --batch-size=${trialParameters.batchSize}
                      - --data-fraction=${trialParameters.dataFraction}
                      - --network-option=num_edge_conv_blocks:${trialParameters.numEdgeConvBlocks},k:${trialParameters.k},num_conv_layers:${trialParameters.numConvLayers},conv_dim:${trialParameters.convDim},num_fc_layers:${trialParameters.numFcLayers},fc_dim:${trialParameters.fcDim},dropout:${trialParameters.dropout}
                      - --tensorboard-log-dir=S3_BUCKET/tensorboard/RUN_ID/${trialParameters.numEdgeConvBlocks}_${trialParameters.k}_${trialParameters.numConvLayers}_${trialParameters.convDim}_${trialParameters.numFcLayers}_${trialParameters.fcDim}_${trialParameters.dropout}_${trialParameters.startLr}_${trialParameters.optimizer}_${trialParameters.numEpochs}_${trialParameters.batchSize}_${trialParameters.dataFraction}
                      - --s3-model=S3_BUCKET/RUN_ID/${trialParameters.numEdgeConvBlocks}_${trialParameters.k}_${trialParameters.numConvLayers}_${trialParameters.convDim}_${trialParameters.numFcLayers}_${trialParameters.fcDim}_${trialParameters.dropout}_${trialParameters.startLr}_${trialParameters.optimizer}_${trialParameters.numEpochs}_${trialParameters.batchSize}_${trialParameters.dataFraction}.pt
          Worker:
            replicas: WORKER_REPLICAS
            restartPolicy: OnFailure
            template:
              metadata:
                annotations:
                  sidecar.istio.io/inject: "false"
              spec:
                volumes:
                  - name: eos
                    hostPath:
                      path: /var/eos
                  - name: krb-secret-vol
                    secret:
                      secretName: krb-secret
                  - name: nvidia-driver
                    hostPath:
                      path: /opt/nvidia-driver
                      type: ""
                containers:
                  - name: pytorch
                    resources: 
                      limits:
                        nvidia.com/gpu: NUM_GPUS
                        cpu: 4
                        memory: 12Gi
                      requests:
                        nvidia.com/gpu: NUM_GPUS
                        cpu: NUM_CPUS
                        memory: 8Gi
                    volumeMounts:
                      - name: eos
                        mountPath: /eos
                      - name: krb-secret-vol
                        mountPath: /secret/krb-secret-vol
                      - name: nvidia-driver
                        mountPath: /opt/nvidia-driver
                    env:
                      - name: S3_ENDPOINT
                        value: https://s3.cern.ch
                      - name: AWS_ACCESS_KEY_ID
                        valueFrom:
                          secretKeyRef:
                            key: AWS_ACCESS_KEY_ID
                            name: s3-secret
                      - name: AWS_SECRET_ACCESS_KEY
                        valueFrom:
                          secretKeyRef:
                            key: AWS_SECRET_ACCESS_KEY
                            name: s3-secret
                    image: registry.cern.ch/ml/weaver:latest
                    command:
                      - python
                      - train.py
                    args:
                      - --gpus=GPU_IDS
                      - --num-workers=NUM_CPUS
                      - --backend=BACKEND
                      - --regression-mode
                      - --copy-inputs
                      - --data-train=DATA_TRAIN
                      - --data-val=DATA_VAL
                      - --data-test=DATA_TEST
                      - --data-config=DATA_CONFIG
                      - --network-config=NETWORK_CONFIG
                      - --start-lr=${trialParameters.startLr}
                      - --optimizer=${trialParameters.optimizer}
                      - --num-epochs=${trialParameters.numEpochs}
                      - --batch-size=${trialParameters.batchSize}
                      - --data-fraction=${trialParameters.dataFraction}
                      - --network-option=num_edge_conv_blocks:${trialParameters.numEdgeConvBlocks},k:${trialParameters.k},num_conv_layers:${trialParameters.numConvLayers},conv_dim:${trialParameters.convDim},num_fc_layers:${trialParameters.numFcLayers},fc_dim:${trialParameters.fcDim},dropout:${trialParameters.dropout}
                      - --tensorboard-log-dir=S3_BUCKET/tensorboard/RUN_ID/${trialParameters.numEdgeConvBlocks}_${trialParameters.k}_${trialParameters.numConvLayers}_${trialParameters.convDim}_${trialParameters.numFcLayers}_${trialParameters.fcDim}_${trialParameters.dropout}_${trialParameters.startLr}_${trialParameters.optimizer}_${trialParameters.numEpochs}_${trialParameters.batchSize}_${trialParameters.dataFraction}
                      - --s3-model=S3_BUCKET/RUN_ID/${trialParameters.numEdgeConvBlocks}_${trialParameters.k}_${trialParameters.numConvLayers}_${trialParameters.convDim}_${trialParameters.numFcLayers}_${trialParameters.fcDim}_${trialParameters.dropout}_${trialParameters.startLr}_${trialParameters.optimizer}_${trialParameters.numEpochs}_${trialParameters.batchSize}_${trialParameters.dataFraction}.pt